=== boeboe/poc-product-service/src/main/resources/webroot/api/product.schema.json
{
  "$schema": "http://json-schema.org/schema",
  "type": "object",
  "title": "Product schema",
  "description": "A product representation",
  "required":false,
  "properties": {
    "id": {
      "type": "string",
      "title": "Id",
      "description": "The id of the product",
      "minLength": 36,
      "maxLength": 36,
      "required": false
    },
    "name": {
      "type": "string",
      "title": "Name",
      "description": "The name of the product",
      "required": true
    },
    "price": {
      "type": "number",
      "title": "Price",
      "description": "The price of the product",
      "required": true
    },
    "weight": {
      "type": "integer",
      "title": "Weight",
      "description": "The weight of the product",
      "required": true
    }
  }
}

=== boeboe/poc-product-service/src/main/resources/webroot/api/products.example.json
[
  {
    "id": "705c2c6b-9261-4248-94ee-787584386a3a",
    "name": "Tea Cosy",
    "price": 5.99,
    "weight": 100
  },
  {
    "id": "ed1116bc-7c7d-4836-9675-2f4aaff224d5",
    "name": "Spatula",
    "price": 1.0,
    "weight": 80
  },
  {
    "id": "ab9c7417-8152-4105-94d5-1b4fd6e360ff",
    "name": "Egg Whisk",
    "price": 3.99,
    "weight": 150
  }
]
